
[mcp_servers.laravel-boost.tools.search-docs]
approval_mode = "approve"

[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
cwd = "/Users/zavodskyd/Code/webs/serial-communication"
